language: generic
sudo: required
dist: trusty


os:
  - linux

env:
  global:
    - DISPLAY=:99.0

before_install:
  - Xvfb $DISPLAY &
  - wget "https://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20amd64%20DEB/Lazarus%201.8.4/fpc_3.0.4-3_amd64.deb/download" -O fpc_3.0.4-3_amd64.deb
  - wget "https://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20amd64%20DEB/Lazarus%201.8.4/fpc-src_3.0.4-2_amd64.deb/download" -O fpc-src_3.0.4-2_amd64.deb
  - wget "https://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20amd64%20DEB/Lazarus%201.8.4/lazarus-project_1.8.4-0_amd64.deb/download" -O lazarus-project_1.8.4-0_amd64.deb
  - ls -lap
install:
  - sudo apt-get install libgtk2.0-dev
  - sudo dpkg -i *.deb

script:
  - git clone https://github.com/paxtibi/paxjson.git     packages/paxjson
  - git clone https://github.com/paxtibi/paxlogging.git  packages/paxlogging
  - git clone https://github.com/paxtibi/paxhttp.git     packages/paxhttp
  - lazbuild --add-package /home/travis/build/paxtibi/jsonserver/packages/paxhttp/pck/paxhttp_package.lpk /home/travis/build/paxtibi/jsonserver/packages/paxjson/pck/paxjson_package.lpk /home/travis/build/paxtibi/jsonserver/packages/paxlogging/pck/paxlogging_package.lpk
  - lazbuild pck/jsonserver.lpi
  
notifications:
  email:
    on_success: false
    on_failure: change
